import { useRouter } from "next/router";
import { Circle } from "@mui/icons-material";
import { Box } from "@mui/material";
import Navbar from "../../src/components/Navbar";
import LoanDetails from "../../src/components/Loan/loan";
import Header_request from "../../src/components/Header_request";
import Footer from "../../src/components/Footer";
import Copyright from "../../src/components/Copyright";
import { useState } from "react";
import Head from "next/head";
const Loan = () => {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    loan: "",
    address: "",
    register: "",
    salary: "",
    description: "",
  });
  const handleForm = async (e) => {
    e.preventDefault();
    const form = {
      name: formData.name,
      email: formData.email,
      loan: formData.loan,
      address: formData.address,
      phone: formData.phone,
      register: formData.register,
      salary: formData.salary,
      description: formData.description,
    };
    const res = fetch("/api/submit", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(form),
    });
    setFormData((formData) => ({
      ...formData,
      name: "",
      email: "",
      phone: "",
      loan: "",
      address: "",
      register: "",
      salary: "",
      description: "",
    }));
  };
  return (
    <>
      <Head>
        <title>Гадаад харилцагч нарт</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/lil_logo.png" />
      </Head>
      <Navbar />
      <span className="h-24"></span>
      <Box
        sx={{
          height: "35vh",
          backgroundImage: "url('/img/contact.jpg')",
          position: "relative",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          backgroundPosition: "center",
          backgroundSize: "cover",
          paddingTop: "48px",
          zIndex: 40,
        }}
      >
        <span className="bg-black opacity-50 absolute inset-0 z-10"></span>
        <div className="text-white relative z-20 text-center flex flex-col items-center">
          <h1 className="text-4xl mb-6 font-semibold uppercase">
            гадаад ЗАХИАЛАГЧ НАРТ
          </h1>
          <div className="flex uppercase relative items-center z-20">
            <h5 className="uppercase mr-4 text-sm tracking-widest">Зээл</h5>
            <Circle
              sx={{ marginRight: "1rem", width: "0.5rem", fill: "#fec405" }}
            />
            <h5 className="uppercase mr-4 text-sm tracking-widest">
              гадаад ЗАХИАЛАГЧ НАРТ
            </h5>
          </div>
        </div>
      </Box>
      <Box
        sx={{
          backgroundImage: {
            lg: 'url("/img/loan_img.png")',
            xl: 'url("/img/loan_img.png")',
            md: "none",
            sm: "none",
            xs: "none",
          },
          backgroundSize: "cover",
          backgroundPosition: "center",
          padding: "10px",
        }}
      >
        <LoanDetails items={"external"} />
      </Box>
      <Box sx={{ height: "140px" }}></Box>

      <Header_request
        handleForm={handleForm}
        formData={formData}
        setFormData={setFormData}
      />
      <Footer />
      <Copyright />
    </>
  );
};

export default Loan;
