import Head from "next/head";
import Image from "next/image";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { i18n } from "../next-i18next.config";
import { useRouter } from "next/router";
import { useState } from "react";
import Link from "next/link";
import Navbar from "../src/components/Navbar";
import Header from "../src/components/Header";
import About from "../src/components/About";
import Projects from "../src/components/Project";
import Loans from "../src/components/Loan";
import Request from "../src/components/Request";
import Footer from "../src/components/Footer";
import Copyright from "../src/components/Copyright";
import Step from "../src/components/Step";
import InternalLoan from "../src/components/Loan_2";
import MiniRequest from "../src/components/MIniRequest";
import { Box } from "@mui/material";
import Condition from "../src/components/Condition";
import HeaderRequest from "../src/components/Header_request";
import emailjs from "emailjs-com";
export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["home"])),
    },
  };
}

function Home(props) {
  // const { t } = useTranslation();
  const [formData, setFormData] = useState({
    name: "",
    phone: "",
    phonePlatform: "",
    platform: "telegram",
    email: "",
    interest: "Хадат Вилла 4",
    address: "",
    salary: "",
    description: "",
    business: "",
  });
  const handleForm = async (e) => {
    e.preventDefault();
    const form = {
      name: formData.name,
      email: formData.email,
      business: formData.business,
      address: formData.address,
      phone: formData.phone,
      phonePlatform: formData.phonePlatform,
      platform: formData.platform,
      salary: formData.salary,
      description: formData.description,
    };
    await emailjs
      .sendForm(
        "service_skc7ad7",
        "template_ghnna5b",
        e.target,
        "KhnK7ZkZxcfRia1FZ"
      )
      .then(
        (result) => {
          console.log(result.text);
        },
        (error) => {
          console.log(error.text);
        }
      );

    const res = fetch("/api/submit", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(form),
    });
    setFormData((formData) => ({
      ...formData,
      name: "",
      email: "",
      phone: "",
      phonePlatform: "",
      platform: "telegram",
      address: "",
      salary: "",
      description: "",
      interest: "Хадат Вилла 4",
      business: "",
    }));
  };

  return (
    <div>
      <Head>
        <title>Нүүр</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/lil_logo.png" />
      </Head>

      <Navbar check_bg={"home"} />
      <Header />
      <Condition />
      <Loans />

      <Box>
        <Step />
      </Box>

      <HeaderRequest />
      <Projects />

      <Request
        handleForm={handleForm}
        formData={formData}
        setFormData={setFormData}
      />
      <Footer />
      <Copyright />
      {/* <div className="mt-screen">{t("home:dorj")}</div> */}
    </div>
  );
}

export default Home;
