import Navbar from "../../src/components/Navbar";
import ProductDetail from "../../src/components/product/Detail_2";
import Picture from "../../src/components/product/Picture_2";
import ProductHeader from "../../src/components/product/Header_2";
import Footer from "../../src/components/Footer";
import Copyright from "../../src/components/Copyright";
import { useState } from "react";
import { Box } from "@mui/material";
import Head from "next/head";
const Product = () => {
  const [start, setStart] = useState(-1);
  return (
    <>
      <Head>
        <title>Төсөл</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/lil_logo.png" />
      </Head>
      {start == -1 && (
        <Box
          sx={{
            marginTop: {
              xs: "82.2px",
              md: "82.2px",
              sm: "82.2px",
              lg: "0",
              xl: "0",
            },
          }}
        >
          <Navbar />
          <span className="h-24"></span>
          <ProductHeader />
          <ProductDetail />

          <div
            id="splide product_picture_2"
            className="product_picture_2"
          ></div>
          <Picture start={start} setStart={setStart} />

          <Footer />
          <Copyright />
        </Box>
      )}
      {start > -1 && (
        <Box>
          {/* <div className="product_picture" id="splide"></div> */}
          <Picture start={start} setStart={setStart} />
        </Box>
      )}
    </>
  );
};
export default Product;
