import Request from "../../src/components/Request";
import { useState } from "react";
import { useRouter } from "next/router";
import Navbar from "../../src/components/Navbar";
import Footer from "../../src/components/Footer";
import CopyRight from "../../src/components/Copyright";
import Head from 'next/head'
const LoanRequest = () => {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    loan: "",
    address: "",
    register: "",
    salary: "",
    description: "",
  });
  const handleForm = async (e) => {
    e.preventDefault();
    const form = {
      name: formData.name,
      email: formData.email,
      loan: formData.loan,
      address: formData.address,
      phone: formData.phone,
      register: formData.register,
      salary: formData.salary,
      description: formData.description,
    };
    const res = fetch("/api/submit", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(form),
    });
    setFormData((formData) => ({
      ...formData,
      name: "",
      email: "",
      phone: "",
      loan: "",
      address: "",
      register: "",
      salary: "",
      description: "",
    }));
  };
  return (
    <>
    <Head>
        <title>Зээлийн хүсэлт</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/lil_logo.png" />
      </Head>
      <Navbar />
      <Request
        handleForm={handleForm}
        formData={formData}
        setFormData={setFormData}
      />
      <Footer />
      <CopyRight />
    </>
  );
};

export default LoanRequest;
