import Request from "../../src/components/Request";
import { useState } from "react";
import { useRouter } from "next/router";
import Navbar from "../../src/components/Navbar";
import Footer from "../../src/components/Footer";
import CopyRight from "../../src/components/Copyright";
import Head from "next/head";
import emailjs from 'emailjs-com'
const LoanRequest = () => {
     const [formData, setFormData] = useState({
          name: "",
    phone: "",
    phonePlatform: "",
    platform: "telegram",
    email: "",
    interest: "Хадат Вилла 4",
    address: "",
    salary: "",
    description: "",
    business: "",
     });
     const [alert, setAlert] = useState(false);
     const handleForm = async (e) => {
          e.preventDefault();
          await emailjs
      .sendForm(
        "service_skc7ad7",
        "template_ghnna5b",
        e.target,
        "KhnK7ZkZxcfRia1FZ"
      )
      .then(
        (result) => {
          console.log(result.text);
        },
        (error) => {
          console.log(error.text);
        }
      );
    e.target.reset();
          const form = {
               name: formData.name,
      email: formData.email,
      business: formData.business,
      address: formData.address,
      phone: formData.phone,
      phonePlatform: formData.phonePlatform,
      platform: formData.platform,
      salary: formData.salary,
      description: formData.description,
          };
          const res = await fetch("/api/submit", {
               method: "POST",
               headers: {
                    Accept: "application/json",
                    "Content-Type": "application/json",
               },
               body: JSON.stringify(form),
          }).then(() => {
               setFormData((formData) => ({
                    ...formData,
                    name: "",
    phone: "",
    phonePlatform: "",
    platform: "telegram",
    email: "",
    interest: "Хадат Вилла 4",
    address: "",
    salary: "",
    description: "",
    business: "",
               }));
          });

          setAlert(true);
     };
     return (
          <>
               <Head>
                    <title>Зээлийн хүсэлт</title>
                    <meta
                         name="description"
                         content="Generated by create next app"
                    />
                    <link rel="icon" href="/img/lil_logo.png" />
               </Head>
               <Navbar />
               <span className="h-24"></span>
               <Request
                    handleForm={handleForm}
                    formData={formData}
                    setFormData={setFormData}
                    alert={alert}
               />
               <Footer />
               <CopyRight />
          </>
     );
};

export default LoanRequest;
